config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#login"
  post '', to: 'users#loginUser', as: "login"

  get 'logout', to: "users#logoutPage", as: "logoutPage"
  # post '', to: "users#logout", as: "logout"

  match 'acceuil', to: 'users#acceuil', via: [:get, :post], as: "acceuil"
  # get 'acceuil', to: 'users#acceuil', as: 'acceuil'
  # post 'acceuil', to: "users#shodanSearch", as: 'shodan_search'
  
  get 'signup', to: 'users#signup', as: "signup"
  post 'createUser', to: 'users#createUser', as: "createUser"

  get "adminPage/:id", to: "users#destroy", as: 'destroy_user'

  get 'adminPage', to: "users#adminPage", as: "adminPage"

  # get '/patients/:id', to: 'patients#show', as: 'patient'
  # match 'photos', to: 'photos#show', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
                        uniqueness: {case_sensitive: false}, 
                        length: {minimum: 3, maximum: 30}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: {case_sensitive: false},
                      format: {with: VALID_EMAIL_REGEX}

    validates :role, inclusion: { in: %w(admin member) }
     # ... other user fields and methods

     has_secure_password
  
    private

    enum role: { admin: 0, member: 1 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def login
        # @user = User.new
        # user = User.find_by(username: params[:user])
        # if user 
        #     redirect_to '/acceuil'
        # end
    end
    
    def loginUser
        # debugger
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            flash[:notice] = "Logged in successfully"
            session[:user_id] = user.id
            if user.role == "admin"
                redirect_to adminPage_path
            else
                redirect_to acceuil_path
            end
        else
            flash.now[:alert] = "Invalid username or password"
            redirect_to ''
        end
    end

    def signup
        if session[:user_id]
            userRole = User.find(session[:user_id])
            if userRole.role == "admin"
                # debugger
                # redirect_to signup_path
            else
                redirect_to acceuil_path
            end
        else
            redirect_to root_path
        end
    end
    
    # def logout
    # end
    
    def logoutPage
        session[:user_id] = nil
        reset_session
        # debugger
        cookies.delete('_test_tech_session')
        flash[:notice] = "Logged out successfully"
        redirect_to root_path
    end

    def acceuil
        if session[:user_id]
            # user = User.find_by(id: params[:xx])
            if params[:ip].present?
                shodan_service = ShodanService.new("aOjRCkLJgA2CwJgG3QnS0oylO7b0MLTS")
                @data = shodan_service.search_ip(params[:ip])
                # render json: @data
            else
                @data = nil
            end
        else
            redirect_to root_path
        end
    end

    # def shodanSearch
    #     if params[:ip].present?
    #         # debugger
    #         shodan_service = ShodanService.new("aOjRCkLJgA2CwJgG3QnS0oylO7b0MLTS")
    #         @data = shodan_service.search_ip(params[:ip])
    #         # @ports = @data["ports"] if @data
    #         # @ports = @data["ports"] if @data
    #         @pff ="hhhhhhh"
    #         # render json: @ports
    #     end
    # end

    def adminPage
        if session[:user_id]
            userRole = User.find(session[:user_id])
            if userRole.role == "admin"
                @users = User.where.not(id: session[:user_id])
                # user_to_exclude = User.find(1)  # Find the user with id 2
                # @users = User.all.excluding(user_to_exclude)
                # @users = User.all
            else
                redirect_to acceuil_path
            end
        else
            redirect_to root_path
        end
    end

    def createUser 
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "you have successfully created new user"
            redirect_to adminPage_path
            
        else
            flash[:alert] = "something went wrong"
            redirect_to signup_path
        end
    end

    def destroy
        debugger
        @userdel = User.find(params[:id])
        @userdel.destroy
        redirect_to adminPage_path, notice: 'User was successfully destroyed.'

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)    
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
    include UsersHelper
end

app/helpers/users_helper.rb
# module UsersHelper
#     def current_user
#         # save the user in the memory if the user is exist
#         @current_user = USer.find(session[:user_id]) if session[:user_id]
#     end

#     def logged_in?
#         # return a boolean with of || , return true if the user is exist false if it else
#         !!current_user
#     end
# end

module UsersHelper
    def current_user
        # Cache the user in memory if it exists and is not already cached
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        # Return a boolean indicating if the user is logged in
        !!current_user
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_navigation.html.erb
<div class="navbar">
<div class="navigation">
        <ul class="elements">
            <li class="element">
                <div class="userPro">
                    <%= image_tag(asset_path("people-roof.png")) %>
                    <%= link_to "Home", acceuil_path %>
                </div>
            </li>
            <% if current_user.role == "admin" %>
                <li class="element">
                    <div class="userPro">
                            <div class="userPro">
                                <%= image_tag(asset_path("user-add.png")) %>
                                <%= link_to "Add_User", signup_path %>
                            </div>
                    </div>
                </li>
            <% end %>
            <% if current_user.role == "admin" %>
                <li class="element">
                    <div class="userPro">
                            <div class="userPro">
                                <%= image_tag(asset_path("users.png")) %>
                                <%= link_to "Users_List", adminPage_path %>
                            </div>
                    </div>
                </li>
            <% end %>
            <li class="element">
                <div class="userPro">
                    <%= image_tag(asset_path("user.png")) %>
                    <%= link_to "Welcome, #{current_user.username}", logoutPage_path%>
                </div>
            </li>
        </ul>
</div>
</div>

app/views/users/_userList.html.erb
<div class="contentContainer">
    
        <div class="tableContainer">
            <table>
                <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Is_active</th>
                    <th></th>
                </tr>
                <% @users.each do |user|%>
                <tr>
                    <td><%= user.id%></td>
                    <td><%= user.username%></td>
                    <td><%= user.email%></td>
                    <td><%= user.role%></td>
                    <td><%= user.is_active%></td>
                    <td class="globalButtonContainer">
                        <div class="buttonsContainer">
                            <div class="editbuttonAction">
                                <%= link_to "Edit" %>
                                <%# <a href="#">Edit</a> %>
                            </div>
                            <div class="deletebuttonAction">
                                <%# <%= link_to "Delete", destroy_user_path(user.id), method: :delete %> 
                                <%= link_to "Delete", destroy_user_path(user.id), data: { confirm: 'Are you sure?' } %>

                                <%# <a href="#">Delete</a> %>
                            </div>
                        </div>
                    </td>
                </tr>
                <%end%>
                <%# <tr>
                    <td>Centro comercial Moctezuma</td>
                    <td>Francisco Chang</td>
                    <td>Mexico</td>
                    <td>Germany</td>
                    <td>Germany</td>
                    <td class="globalButtonContainer">
                        <div class="buttonsContainer">
                            <div class="editbuttonAction">
                                <a href="#">Edit</a>
                            </div>
                            <div class="deletebuttonAction">
                                <a href="#">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr> %>
            </table>
        </div>
    </div>

app/views/users/acceuil.html.erb
<style>
* {
    margin: 0;
    padding: 0;
}

body {
    background-color: #f2f2f2;
}

.globalContainer {
    background-image: url(<%= asset_path("pff.jpg")%>);
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    height: 80vh;
    display: flex;
    align-items: center;
    justify-content: center;
}

.searchContainer {
    /* background-color: red; */
    display: flex;
    flex-direction: column;
    align-items: center;
    width: auto;
}

.inputContainer {
    display: flex;
    text-align: center;
    justify-content: center;
    align-items: center; 
    /* background-color: green; */
}

.inputSameWidth {
    display: flex;
    width: 500px;
    height: 50px;
}

.inputSearch {
    width: 100%;
    box-sizing: border-box;
    border: 1px solid #333;
    font-size: 1.1rem;
    background-color: rgba(51, 51, 51, 0.6);
    border-radius: 10px 0 0 10px;
    color: white;
    padding-left: 10px;
}

.inputSearch::placeholder {
    color: white;
}

.iconSearch {
    background-color: rgba(51, 51, 51, 0.6);
    border: 1px solid #333;
    margin-left: 5px;
    padding: 12px;
    border-radius: 0 10px 10px 0;
    cursor: pointer;
}

.titleInfo {
    font-size: 2rem;
    color: white;
    margin-top: 30px;
}

.globalContentContainer {
    display: flex;
    justify-content: center;
}

.contentContainer {
    display: flex;
    justify-content: center;
    width: 70%;
}

.ipInfoContainer {
    display: flex;
    justify-content: space-between;
    width: 100%;
    margin: 50px 0;
}

.otherInfoContainer {
    width: 45%;
    background-color: white;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 10px;
    padding: 20px 10px;
    border-top: 3px solid orange;
}

.ipElementsInfo {
    display: flex;
    flex-direction: column;
    /* margin: 0 25px; */
    padding: 10px 20px;

}

.ipElementsInfo li {
    display: flex;
    margin-top: 10px;
    font-size: 1.2rem;
    list-style-type: none;
}

.elementName {
    width: 50%;
}

.ipInfo {
    width: 45%;
    background-color: white;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 10px;
    padding: 20px 10px;
    border-top: 3px solid green;
}

.ipInfoTitle {
    font-size: 1.5rem;
    padding-left: 10px;
}

.ipElements {
    display: flex;
    padding: 10px 20px;
}

.portElement {
    border: 1px solid white;
    border-radius: 3px;
    padding: 10px;
    margin: 0 10px;
    list-style-type: none;
    background-color: green;
    color: white;
}

</style>
<div>
    <div class="globalContainer">
        <%= render "navigation" %>
        <div class="searchContainer">
            <%= form_with url: acceuil_path, local: true do |f| %>
                <div class="inputContainer">
                    <div class="inputSameWidth">
                        <%# <input type="text" id="search" placeholder="search an ip" class="inputSearch"/> %>
                        <%= f.text_field :ip, class: "inputSearch", id: "search", placeholder: "search an ip"%>
                        <%# <%= f.submit image_tag(asset_path('search-location.png'), alt: "Image Alt Text"), class: "iconSearch" %> 
                        <%= button_to " ", method: :get, remote: true, data: { information: "some_value" }, class: "iconSearch" do %>
                            <%= image_tag("search-location.png", alt: "Button Text") %>
                        <% end %>
                    </div>
                </div>
                <div class="titleInfo">
                    <p>Find What You Need: Your IP Search Starts Now!</p>
                </div>
            <% end %>
        </div>
    </div>
</div>

    <div class="globalContentContainer">
        <div class="contentContainer">
            <div class="ipInfoContainer">
                <div class="otherInfoContainer">
                    <div class="otherInfo">
                        <p class="ipInfoTitle">Global <span style="font-weight: bold">Information</span></p>
                        <ul class="ipElementsInfo">
                            <% if @data%>
                                <li>
                                    <div class="elementName">
                                        <p>city </p>
                                    </div>
                                    <div class="elementName">
                                        <p style="font-weight: bold;"><%= @data['city']%></p>
                                    </div>
                                </li>
                                <li>
                                    <div class="elementName">
                                        <p>region_code </p>
                                    </div>
                                    <div class="elementName">
                                        <p style="font-weight: bold;"><%= @data['region_code']%></p>
                                    </div>
                                </li>
                                <li>
                                    <div class="elementName">
                                        <p>ip </p>
                                    </div>
                                    <div class="elementName">
                                        <p style="font-weight: bold;"><%= @data['ip']%></p>
                                    </div>
                                </li>
                                <li>
                                    <div class="elementName">
                                        <p>isp </p>
                                    </div>
                                    <div class="elementName">
                                        <p style="font-weight: bold;"><%= @data['isp']%></p>
                                    </div>
                                </li>
                            <% else %>
                                <p style="color: orange;">there is no data! (try to search on the search bar)</p>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="ipInfo">
                    <p class="ipInfoTitle">open <span style="font-weight: bold">Ports</span></p>
                    <ul class="ipElements">
                        <% if @data%>
                            <% @data['ports'].each do |port| %>
                            <li class='portElement'>
                                <span id="ipAddress"><%= port%></span>
                            </li>
                            <%end%>
                        <% else %>
                            <p style="color: green;">there is no data! (try to search on the search bar)</p>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>

    </div>

app/views/users/adminPage.html.erb
        <%# <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title> %>
        <%# <link rel="stylesheet" href="navigation.css"> %>

    <div>
        <div >
            <div class="globalContainerAdminPage">
                <%= render "navigation" %>
                <div class="TitleInfoAdminPage">
                    <p>Users List Page</p>
                </div>
            </div>

        </div>
        <%= render "userList"%>
    </div>

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'login', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="globalLoginContainer">
        <div class="loginContainer">

            <div class="titleContainer">
                <h1 class="title">Login</h1>
            </div>

            <div class="formContainer" >
            <%# <form class="formContainer"> %>
            <%=form_with scope: :user, url: login_path, local: true, method: :post do |f| %>
                <div class="inputContainer">
                    <%=image_tag(asset_path("user.png"), class: "inputIcon")%>
                    <%= f.text_field :username, class: "inputField", placeholder: "Username" %>
                </div>
    
                <div class="inputContainer">
                    <%=image_tag(asset_path("lock.png"), class: "inputIcon")%>
                    <%= f.password_field :password, class: "inputField", placeholder: "Password"%>
                </div>

                <div class="buttonContainer">
                    <%= f.submit "Login", class: "button"%>
                </div>
            <% end %>
            </div>
            <%# </form> %>
        </div>
    </div>
</body>
</html>

app/views/users/signup.html.erb
<%# <%= stylesheet_link_tag('signup')  %>


    <div class="globalContainer">
        <%# <div class="navbar">
            <div class="navigation">
                <ul class="elements">
                    <li class="element">
                        <div class="userPro"> %>
                            <%# <%= image_tag(asset_path("users.png")) %>
                            <%# <%= link_to "Users_List", adminPage_path %> 
                        <%# </div>
                    </li>
                    <li class="element">
                        <div class="userPro"> %>
                            <%# <%= image_tag(asset_path("user.png")) %>
                            <%# <p>Hello, Foulen</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div> %>
        <%= render "navigation"%>
    <div>
        <div class="localContainer">
            <div>
                <div class="centerTitle">
                    <h1 class="loginTitle">Create User</h1>
                </div>
                <div class="formContainerSignup">
                    <%= form_with scope: :user, url: createUser_path, local: true, method: :post do |f| %>
                        <div class="formGroup">
                            <%= f.text_field :username, class: "inputField", placeholder: "Username" %>
                            <%= image_tag(image_path("user.png"), class: "inputIconSignup")%>
                        </div>

                        <div class="formGroup">
                            <%= f.email_field :email, class: "inputFieldSignup", placeholder: "Email" %>
                            <%= image_tag(image_path("envelope.png"), class: "inputIconSignup")%>
                        </div>

                        <div class="formGroup">
                            <%= f.password_field :password, class: "inputFieldSignup", placeholder: "password" %>
                            <%= image_tag(image_path("lock.png"), class: "inputIconSignup") %>
                        </div>

                        <div class="buttonContainerSignup">
                            <div class="buttonSignup">
                                <%= f.submit "Add User", class: "btn" %>
                            </div>
                        </div>

                    <% end %>
                </div>

            </div>
        </div>
    </div>


  </div>
<%# </html> %>